print("Welcome to the band Name Generator.")
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
name = input()
print("Your band name is " + city + " " + name)